/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.requisigner;

import org.junit.jupiter.api.Test;
import org.requisigner.Requisigner;

import static org.junit.jupiter.api.Assertions.*;

class RequisignerTest {
    @Test void appHasAGreeting() {
        
    }
}
