/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.quillsigner;

import org.junit.jupiter.api.Test;
import org.quillsigner.QuillSigner;

import static org.junit.jupiter.api.Assertions.*;

class QuillSignerTest {
    @Test void appHasAGreeting() {
        QuillSigner classUnderTest = new QuillSigner("");
    }
}
